# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class Input:
    pass

class Output:
    CC = "cc"
    COUNTRY = "country"
    IP = "ip"
    

class LookupInput(komand.Input):
    schema = json.loads("""
   {}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class LookupOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "cc": {
      "type": "string",
      "title": "Country Code",
      "description": "Country code e.g. US",
      "order": 3
    },
    "country": {
      "type": "string",
      "title": "Country",
      "description": "Country name",
      "order": 2
    },
    "ip": {
      "type": "string",
      "title": "IP Address",
      "description": "The public routable IP address",
      "order": 1
    }
  },
  "required": [
    "country",
    "cc",
    "ip"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
